apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mlops-airflow
  namespace: airflow
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: airflow
      version: "1.18.0"
      sourceRef:
        kind: HelmRepository
        name: apache-airflow
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Airflow version
    airflowVersion: "3.1.13"

    # Executor - KubernetesExecutor for scalability
    executor: "KubernetesExecutor"

    # Security - Use Kubernetes secrets for sensitive data
    # Create secrets using: kubectl create secret generic <name> --from-literal=<key>=<value> -n airflow
    # See SECRETS-SETUP.md for detailed instructions
    webserverSecretKeySecretName: "airflow-webserver-secret"
    fernetKeySecretName: "airflow-fernet-key"

    # Disable Helm hooks for GitOps workflow
    createUserJob:
      useHelmHooks: false
      applyCustomEnv: false
    migrateDatabaseJob:
      useHelmHooks: false
      applyCustomEnv: false

    postgresql:
         enabled: true
         image:
           registry: docker.io
           repository: bitnamilegacy/postgresql
           tag: 17.6.0-debian-12-r4

    # Git-sync configuration for DAGs
    dags:
      gitSync:
        enabled: true
        repo: git@github.com:HSLU-DBIZ/JobMonitor-DAGs.git
        branch: main
        subPath: ""
        sshKeySecret: flux-git-ssh
        wait: 60
        maxFailures: 0
      persistence:
        enabled: false  # Disabled when using git-sync

    # Webserver configuration
    webserver:
      replicas: 1
      service:
        type: ClusterIP
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 512Mi
      livenessProbe:
        initialDelaySeconds: 15
        periodSeconds: 10
      readinessProbe:
        initialDelaySeconds: 15
        periodSeconds: 10

    # Scheduler configuration
    scheduler:
      replicas: 1
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 512Mi
      livenessProbe:
        initialDelaySeconds: 15
        periodSeconds: 10

    # Triggerer configuration (for deferrable operators)
    triggerer:
      enabled: true
      replicas: 1
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 200m
          memory: 512Mi

    # Redis (required for CeleryExecutor, optional for KubernetesExecutor)
    redis:
      enabled: false  # Set to true if using CeleryExecutor

    # StatsD metrics
    statsd:
      enabled: true
      overrideMappings: []
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi

    # PgBouncer (connection pooling)
    pgbouncer:
      enabled: false  # Enable for production with high connection counts
      maxClientConn: 100
      metadataPoolSize: 10
      resultBackendPoolSize: 5

    # Log persistence
    logs:
      persistence:
        enabled: true
        size: 10Gi
        storageClassName: ""  # Use default storage class

    # Airflow configuration overrides
    config:
      core:
        load_examples: true
      webserver:
        expose_config: false
        enable_proxy_fix: true
      logging:
        remote_logging: false
      metrics:
        statsd_on: true
        statsd_host: localhost
        statsd_port: 9125
      scheduler:
        run_duration: 41460
        statsd_on: true

    # Security context
    securityContext:
      runAsUser: 50000
      fsGroup: 0

    # RBAC
    rbac:
      create: true
      createSCCRoleBinding: false
