apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mlops-airflow
  namespace: airflow
spec:
  interval: 10m
  timeout: 10m
  chart:
    spec:
      chart: airflow
      version: "1.15.0"
      sourceRef:
        kind: HelmRepository
        name: apache-airflow
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Airflow configuration
    createUserJob:
      useHelmHooks: false
      applyCustomEnv: false
    migrateDatabaseJob:
      useHelmHooks: false
      applyCustomEnv: false

    # Git-sync configuration for DAGs
    dags:
      gitSync:
        enabled: true
        repo: git@github.com:HSLU-DBIZ/JobMonitor-DAGs.git
        branch: main
        subPath: ""
        sshKeySecret: flux-git-ssh
